server:
  shutdown: graceful
  port: 8080
spring:
  application:
  name: inflearn-spring-ai-study
  config:
    import: optional:file:.env[.properties] # config env file using


logging:
  level:
    root: INFO

# LLM SERVICE
llm:
  gpt:
    key: ${GPT_API_KEY:"gpt-api"}
  gemini:
    key: ${GEMINI_API_KEY:"gemini-api"}

springdoc:
  swagger-ui:
    path: /docs
    use-root-path: false
  api-docs:
    enabled: true
    path: /api-docs
  model-and-view-allowed: false
